DELIMITER $$

CREATE PROCEDURE Insertar_actividad (IN p_ID_PROGRAMA int, IN p_NOMBRE_AVTIVI varchar(60), IN p_DESCRIPCION_ACTIVI text, IN p_DURACION_ACTIVI int, IN p_FINALIZADO tinyint(1)) 
BEGIN
    INSERT INTO actividad (ID_PROGRAMA, NOMBRE_AVTIVI, DESCRIPCION_ACTIVI, DURACION_ACTIVI, FINALIZADO) VALUES (p_ID_PROGRAMA, p_NOMBRE_AVTIVI, p_DESCRIPCION_ACTIVI, p_DURACION_ACTIVI, p_FINALIZADO);
END $$

CREATE PROCEDURE Actualizar_actividad (IN p_ID_ACTIVIDAD int, IN p_ID_PROGRAMA int, IN p_NOMBRE_AVTIVI varchar(60), IN p_DESCRIPCION_ACTIVI text, IN p_DURACION_ACTIVI int, IN p_FINALIZADO tinyint(1)) 
BEGIN
    UPDATE actividad SET ID_PROGRAMA = p_ID_PROGRAMA, NOMBRE_AVTIVI = p_NOMBRE_AVTIVI, DESCRIPCION_ACTIVI = p_DESCRIPCION_ACTIVI, DURACION_ACTIVI = p_DURACION_ACTIVI, FINALIZADO = p_FINALIZADO WHERE ID_ACTIVIDAD = p_ID_ACTIVIDAD;
END $$

CREATE PROCEDURE Eliminar_actividad (IN p_ID_ACTIVIDAD int) 
BEGIN
    DELETE FROM actividad WHERE ID_ACTIVIDAD = p_ID_ACTIVIDAD;
END $$

CREATE PROCEDURE ObtenerTodos_actividad () 
BEGIN
    SELECT * FROM actividad;
END $$

CREATE PROCEDURE Insertar_alergias (IN p_NOMBRE_ALERGIA varchar(30)) 
BEGIN
    INSERT INTO alergias (NOMBRE_ALERGIA) VALUES (p_NOMBRE_ALERGIA);
END $$

CREATE PROCEDURE Actualizar_alergias (IN p_ID_ALERGIA int, IN p_NOMBRE_ALERGIA varchar(30)) 
BEGIN
    UPDATE alergias SET NOMBRE_ALERGIA = p_NOMBRE_ALERGIA WHERE ID_ALERGIA = p_ID_ALERGIA;
END $$

CREATE PROCEDURE Eliminar_alergias (IN p_ID_ALERGIA int) 
BEGIN
    DELETE FROM alergias WHERE ID_ALERGIA = p_ID_ALERGIA;
END $$

CREATE PROCEDURE ObtenerTodos_alergias () 
BEGIN
    SELECT * FROM alergias;
END $$

CREATE PROCEDURE Insertar_ano_lectivo (IN p_ANO varchar(4)) 
BEGIN
    INSERT INTO ano_lectivo (ANO) VALUES (p_ANO);
END $$

CREATE PROCEDURE Actualizar_ano_lectivo (IN p_ID_ANO_LECTIVO int, IN p_ANO varchar(4)) 
BEGIN
    UPDATE ano_lectivo SET ANO = p_ANO WHERE ID_ANO_LECTIVO = p_ID_ANO_LECTIVO;
END $$

CREATE PROCEDURE Eliminar_ano_lectivo (IN p_ID_ANO_LECTIVO int) 
BEGIN
    DELETE FROM ano_lectivo WHERE ID_ANO_LECTIVO = p_ID_ANO_LECTIVO;
END $$

CREATE PROCEDURE ObtenerTodos_ano_lectivo () 
BEGIN
    SELECT * FROM ano_lectivo;
END $$

CREATE PROCEDURE Insertar_emplea (IN p_ID_MATERIAL int, IN p_ID_ACTIVIDAD int) 
BEGIN
    INSERT INTO emplea (ID_MATERIAL, ID_ACTIVIDAD) VALUES (p_ID_MATERIAL, p_ID_ACTIVIDAD);
END $$

CREATE PROCEDURE ObtenerTodos_emplea () 
BEGIN
    SELECT * FROM emplea;
END $$

CREATE PROCEDURE Insertar_estado_salud (IN p_ID_NINIO int, IN p_ULTIMA_FECHA_ENFERMO date, IN p_DIAGNOSTICO text, IN p_DOCTOR_TRATANTE varchar(60)) 
BEGIN
    INSERT INTO estado_salud (ID_NINIO, ULTIMA_FECHA_ENFERMO, DIAGNOSTICO, DOCTOR_TRATANTE) VALUES (p_ID_NINIO, p_ULTIMA_FECHA_ENFERMO, p_DIAGNOSTICO, p_DOCTOR_TRATANTE);
END $$

CREATE PROCEDURE Actualizar_estado_salud (IN p_ID_SALUD_STAT int, IN p_ID_NINIO int, IN p_ULTIMA_FECHA_ENFERMO date, IN p_DIAGNOSTICO text, IN p_DOCTOR_TRATANTE varchar(60)) 
BEGIN
    UPDATE estado_salud SET ID_NINIO = p_ID_NINIO, ULTIMA_FECHA_ENFERMO = p_ULTIMA_FECHA_ENFERMO, DIAGNOSTICO = p_DIAGNOSTICO, DOCTOR_TRATANTE = p_DOCTOR_TRATANTE WHERE ID_SALUD_STAT = p_ID_SALUD_STAT;
END $$

CREATE PROCEDURE Eliminar_estado_salud (IN p_ID_SALUD_STAT int) 
BEGIN
    DELETE FROM estado_salud WHERE ID_SALUD_STAT = p_ID_SALUD_STAT;
END $$

CREATE PROCEDURE ObtenerTodos_estado_salud () 
BEGIN
    SELECT * FROM estado_salud;
END $$

CREATE PROCEDURE Insertar_genero (IN p_NOMBRE_GENERO varchar(30)) 
BEGIN
    INSERT INTO genero (NOMBRE_GENERO) VALUES (p_NOMBRE_GENERO);
END $$

CREATE PROCEDURE Actualizar_genero (IN p_ID_GENERO int, IN p_NOMBRE_GENERO varchar(30)) 
BEGIN
    UPDATE genero SET NOMBRE_GENERO = p_NOMBRE_GENERO WHERE ID_GENERO = p_ID_GENERO;
END $$

CREATE PROCEDURE Eliminar_genero (IN p_ID_GENERO int) 
BEGIN
    DELETE FROM genero WHERE ID_GENERO = p_ID_GENERO;
END $$

CREATE PROCEDURE ObtenerTodos_genero () 
BEGIN
    SELECT * FROM genero;
END $$

CREATE PROCEDURE Insertar_material (IN p_NOMBRE_MATERIAL varchar(30)) 
BEGIN
    INSERT INTO material (NOMBRE_MATERIAL) VALUES (p_NOMBRE_MATERIAL);
END $$

CREATE PROCEDURE Actualizar_material (IN p_ID_MATERIAL int, IN p_NOMBRE_MATERIAL varchar(30)) 
BEGIN
    UPDATE material SET NOMBRE_MATERIAL = p_NOMBRE_MATERIAL WHERE ID_MATERIAL = p_ID_MATERIAL;
END $$

CREATE PROCEDURE Eliminar_material (IN p_ID_MATERIAL int) 
BEGIN
    DELETE FROM material WHERE ID_MATERIAL = p_ID_MATERIAL;
END $$

CREATE PROCEDURE ObtenerTodos_material () 
BEGIN
    SELECT * FROM material;
END $$

CREATE PROCEDURE Insertar_matricula (IN p_ID_NINIO int, IN p_ID_ANO_LECTIVO int, IN p_PRECIO_MATRICULA int) 
BEGIN
    INSERT INTO matricula (ID_NINIO, ID_ANO_LECTIVO, PRECIO_MATRICULA) VALUES (p_ID_NINIO, p_ID_ANO_LECTIVO, p_PRECIO_MATRICULA);
END $$

CREATE PROCEDURE Actualizar_matricula (IN p_ID_MATRICULA int, IN p_ID_NINIO int, IN p_ID_ANO_LECTIVO int, IN p_PRECIO_MATRICULA int) 
BEGIN
    UPDATE matricula SET ID_NINIO = p_ID_NINIO, ID_ANO_LECTIVO = p_ID_ANO_LECTIVO, PRECIO_MATRICULA = p_PRECIO_MATRICULA WHERE ID_MATRICULA = p_ID_MATRICULA;
END $$

CREATE PROCEDURE Eliminar_matricula (IN p_ID_MATRICULA int) 
BEGIN
    DELETE FROM matricula WHERE ID_MATRICULA = p_ID_MATRICULA;
END $$

CREATE PROCEDURE ObtenerTodos_matricula () 
BEGIN
    SELECT * FROM matricula;
END $$

CREATE PROCEDURE Insertar_medicamento (IN p_NOMBRE_MEDICAMENTO varchar(30), IN p_DESCRIPTION_MEDICAMENTO text) 
BEGIN
    INSERT INTO medicamento (NOMBRE_MEDICAMENTO, DESCRIPTION_MEDICAMENTO) VALUES (p_NOMBRE_MEDICAMENTO, p_DESCRIPTION_MEDICAMENTO);
END $$

CREATE PROCEDURE Actualizar_medicamento (IN p_ID_MEDICAMENTO int, IN p_NOMBRE_MEDICAMENTO varchar(30), IN p_DESCRIPTION_MEDICAMENTO text) 
BEGIN
    UPDATE medicamento SET NOMBRE_MEDICAMENTO = p_NOMBRE_MEDICAMENTO, DESCRIPTION_MEDICAMENTO = p_DESCRIPTION_MEDICAMENTO WHERE ID_MEDICAMENTO = p_ID_MEDICAMENTO;
END $$

CREATE PROCEDURE Eliminar_medicamento (IN p_ID_MEDICAMENTO int) 
BEGIN
    DELETE FROM medicamento WHERE ID_MEDICAMENTO = p_ID_MEDICAMENTO;
END $$

CREATE PROCEDURE ObtenerTodos_medicamento () 
BEGIN
    SELECT * FROM medicamento;
END $$

CREATE PROCEDURE Insertar_nacionalidad (IN p_NOMBRE_NACIONALIDAD varchar(30)) 
BEGIN
    INSERT INTO nacionalidad (NOMBRE_NACIONALIDAD) VALUES (p_NOMBRE_NACIONALIDAD);
END $$

CREATE PROCEDURE Actualizar_nacionalidad (IN p_ID_NACIONALIDAD int, IN p_NOMBRE_NACIONALIDAD varchar(30)) 
BEGIN
    UPDATE nacionalidad SET NOMBRE_NACIONALIDAD = p_NOMBRE_NACIONALIDAD WHERE ID_NACIONALIDAD = p_ID_NACIONALIDAD;
END $$

CREATE PROCEDURE Eliminar_nacionalidad (IN p_ID_NACIONALIDAD int) 
BEGIN
    DELETE FROM nacionalidad WHERE ID_NACIONALIDAD = p_ID_NACIONALIDAD;
END $$

CREATE PROCEDURE ObtenerTodos_nacionalidad () 
BEGIN
    SELECT * FROM nacionalidad;
END $$

CREATE PROCEDURE Insertar_ninio (IN p_ID_NACIONALIDAD int, IN p_ID_GENERO int, IN p_ID_TALLA_ZAPATO int, IN p_ID_TALLA_VESTIMENTA int, IN p_CI_NINIO varchar(10), IN p_NOMBRE_NINIO varchar(30), IN p_APELLIDO_NINIO varchar(30), IN p_NACIMIENTO_DATE date, IN p_ESTADO_MATRICULA tinyint(1)) 
BEGIN
    INSERT INTO ninio (ID_NACIONALIDAD, ID_GENERO, ID_TALLA_ZAPATO, ID_TALLA_VESTIMENTA, CI_NINIO, NOMBRE_NINIO, APELLIDO_NINIO, NACIMIENTO_DATE, ESTADO_MATRICULA) VALUES (p_ID_NACIONALIDAD, p_ID_GENERO, p_ID_TALLA_ZAPATO, p_ID_TALLA_VESTIMENTA, p_CI_NINIO, p_NOMBRE_NINIO, p_APELLIDO_NINIO, p_NACIMIENTO_DATE, p_ESTADO_MATRICULA);
END $$

CREATE PROCEDURE Actualizar_ninio (IN p_ID_NINIO int, IN p_ID_NACIONALIDAD int, IN p_ID_GENERO int, IN p_ID_TALLA_ZAPATO int, IN p_ID_TALLA_VESTIMENTA int, IN p_CI_NINIO varchar(10), IN p_NOMBRE_NINIO varchar(30), IN p_APELLIDO_NINIO varchar(30), IN p_NACIMIENTO_DATE date, IN p_ESTADO_MATRICULA tinyint(1)) 
BEGIN
    UPDATE ninio SET ID_NACIONALIDAD = p_ID_NACIONALIDAD, ID_GENERO = p_ID_GENERO, ID_TALLA_ZAPATO = p_ID_TALLA_ZAPATO, ID_TALLA_VESTIMENTA = p_ID_TALLA_VESTIMENTA, CI_NINIO = p_CI_NINIO, NOMBRE_NINIO = p_NOMBRE_NINIO, APELLIDO_NINIO = p_APELLIDO_NINIO, NACIMIENTO_DATE = p_NACIMIENTO_DATE, ESTADO_MATRICULA = p_ESTADO_MATRICULA WHERE ID_NINIO = p_ID_NINIO;
END $$

CREATE PROCEDURE Eliminar_ninio (IN p_ID_NINIO int) 
BEGIN
    DELETE FROM ninio WHERE ID_NINIO = p_ID_NINIO;
END $$

CREATE PROCEDURE ObtenerTodos_ninio () 
BEGIN
    SELECT * FROM ninio;
END $$

CREATE PROCEDURE Insertar_padre (IN p_ID_GENERO int, IN p_ID_NACIONALIDAD int, IN p_NOMBRE_PADRE varchar(30), IN p_APELLIDO_PADRE varchar(30), IN p_CI_PADRE varchar(10), IN p_DIRECCION_PADRE varchar(30), IN p_TELEFONO_PADRE varchar(10), IN p_DOMICILIO_PADRE varchar(30)) 
BEGIN
    INSERT INTO padre (ID_GENERO, ID_NACIONALIDAD, NOMBRE_PADRE, APELLIDO_PADRE, CI_PADRE, DIRECCION_PADRE, TELEFONO_PADRE, DOMICILIO_PADRE) VALUES (p_ID_GENERO, p_ID_NACIONALIDAD, p_NOMBRE_PADRE, p_APELLIDO_PADRE, p_CI_PADRE, p_DIRECCION_PADRE, p_TELEFONO_PADRE, p_DOMICILIO_PADRE);
END $$

CREATE PROCEDURE Actualizar_padre (IN p_ID_PADRE int, IN p_ID_GENERO int, IN p_ID_NACIONALIDAD int, IN p_NOMBRE_PADRE varchar(30), IN p_APELLIDO_PADRE varchar(30), IN p_CI_PADRE varchar(10), IN p_DIRECCION_PADRE varchar(30), IN p_TELEFONO_PADRE varchar(10), IN p_DOMICILIO_PADRE varchar(30)) 
BEGIN
    UPDATE padre SET ID_GENERO = p_ID_GENERO, ID_NACIONALIDAD = p_ID_NACIONALIDAD, NOMBRE_PADRE = p_NOMBRE_PADRE, APELLIDO_PADRE = p_APELLIDO_PADRE, CI_PADRE = p_CI_PADRE, DIRECCION_PADRE = p_DIRECCION_PADRE, TELEFONO_PADRE = p_TELEFONO_PADRE, DOMICILIO_PADRE = p_DOMICILIO_PADRE WHERE ID_PADRE = p_ID_PADRE;
END $$

CREATE PROCEDURE Eliminar_padre (IN p_ID_PADRE int) 
BEGIN
    DELETE FROM padre WHERE ID_PADRE = p_ID_PADRE;
END $$

CREATE PROCEDURE ObtenerTodos_padre () 
BEGIN
    SELECT * FROM padre;
END $$

CREATE PROCEDURE Insertar_profesional (IN p_ID_ACTIVIDAD int, IN p_ID_GENERO int, IN p_ID_NACIONALIDAD int, IN p_NOMBRES_PROF varchar(30), IN p_APELLIDOS_PROF varchar(30), IN p_CI_PROF varchar(10), IN p_DIRECCION_PROF varchar(60), IN p_TELEFONO_PROF varchar(10), IN p_NO_CERTIFI_SENECYT char(15)) 
BEGIN
    INSERT INTO profesional (ID_ACTIVIDAD, ID_GENERO, ID_NACIONALIDAD, NOMBRES_PROF, APELLIDOS_PROF, CI_PROF, DIRECCION_PROF, TELEFONO_PROF, NO_CERTIFI_SENECYT) VALUES (p_ID_ACTIVIDAD, p_ID_GENERO, p_ID_NACIONALIDAD, p_NOMBRES_PROF, p_APELLIDOS_PROF, p_CI_PROF, p_DIRECCION_PROF, p_TELEFONO_PROF, p_NO_CERTIFI_SENECYT);
END $$

CREATE PROCEDURE Actualizar_profesional (IN p_ID_PROF int, IN p_ID_ACTIVIDAD int, IN p_ID_GENERO int, IN p_ID_NACIONALIDAD int, IN p_NOMBRES_PROF varchar(30), IN p_APELLIDOS_PROF varchar(30), IN p_CI_PROF varchar(10), IN p_DIRECCION_PROF varchar(60), IN p_TELEFONO_PROF varchar(10), IN p_NO_CERTIFI_SENECYT char(15)) 
BEGIN
    UPDATE profesional SET ID_ACTIVIDAD = p_ID_ACTIVIDAD, ID_GENERO = p_ID_GENERO, ID_NACIONALIDAD = p_ID_NACIONALIDAD, NOMBRES_PROF = p_NOMBRES_PROF, APELLIDOS_PROF = p_APELLIDOS_PROF, CI_PROF = p_CI_PROF, DIRECCION_PROF = p_DIRECCION_PROF, TELEFONO_PROF = p_TELEFONO_PROF, NO_CERTIFI_SENECYT = p_NO_CERTIFI_SENECYT WHERE ID_PROF = p_ID_PROF;
END $$

CREATE PROCEDURE Eliminar_profesional (IN p_ID_PROF int) 
BEGIN
    DELETE FROM profesional WHERE ID_PROF = p_ID_PROF;
END $$

CREATE PROCEDURE ObtenerTodos_profesional () 
BEGIN
    SELECT * FROM profesional;
END $$

CREATE PROCEDURE Insertar_programa (IN p_ID_ANO_LECTIVO int, IN p_NOMBRE_PROGRAMA varchar(60)) 
BEGIN
    INSERT INTO programa (ID_ANO_LECTIVO, NOMBRE_PROGRAMA) VALUES (p_ID_ANO_LECTIVO, p_NOMBRE_PROGRAMA);
END $$

CREATE PROCEDURE Actualizar_programa (IN p_ID_PROGRAMA int, IN p_ID_ANO_LECTIVO int, IN p_NOMBRE_PROGRAMA varchar(60)) 
BEGIN
    UPDATE programa SET ID_ANO_LECTIVO = p_ID_ANO_LECTIVO, NOMBRE_PROGRAMA = p_NOMBRE_PROGRAMA WHERE ID_PROGRAMA = p_ID_PROGRAMA;
END $$

CREATE PROCEDURE Eliminar_programa (IN p_ID_PROGRAMA int) 
BEGIN
    DELETE FROM programa WHERE ID_PROGRAMA = p_ID_PROGRAMA;
END $$

CREATE PROCEDURE ObtenerTodos_programa () 
BEGIN
    SELECT * FROM programa;
END $$

CREATE PROCEDURE Insertar_relacion (IN p_NOMBRE_PARENTESCO varchar(30)) 
BEGIN
    INSERT INTO relacion (NOMBRE_PARENTESCO) VALUES (p_NOMBRE_PARENTESCO);
END $$

CREATE PROCEDURE Actualizar_relacion (IN p_ID_PARENTESCO int, IN p_NOMBRE_PARENTESCO varchar(30)) 
BEGIN
    UPDATE relacion SET NOMBRE_PARENTESCO = p_NOMBRE_PARENTESCO WHERE ID_PARENTESCO = p_ID_PARENTESCO;
END $$

CREATE PROCEDURE Eliminar_relacion (IN p_ID_PARENTESCO int) 
BEGIN
    DELETE FROM relacion WHERE ID_PARENTESCO = p_ID_PARENTESCO;
END $$

CREATE PROCEDURE ObtenerTodos_relacion () 
BEGIN
    SELECT * FROM relacion;
END $$

CREATE PROCEDURE Insertar_relationship_15 (IN p_ID_PADRE int, IN p_ID_NINIO int) 
BEGIN
    INSERT INTO relationship_15 (ID_PADRE, ID_NINIO) VALUES (p_ID_PADRE, p_ID_NINIO);
END $$

CREATE PROCEDURE ObtenerTodos_relationship_15 () 
BEGIN
    SELECT * FROM relationship_15;
END $$

CREATE PROCEDURE Insertar_rendimiento (IN p_ID_ACTIVIDAD int, IN p_ID_TIPO_RENDIMIENT int, IN p_ID_NINIO int, IN p_OBSERVACIONES text) 
BEGIN
    INSERT INTO rendimiento (ID_ACTIVIDAD, ID_TIPO_RENDIMIENT, ID_NINIO, OBSERVACIONES) VALUES (p_ID_ACTIVIDAD, p_ID_TIPO_RENDIMIENT, p_ID_NINIO, p_OBSERVACIONES);
END $$

CREATE PROCEDURE Actualizar_rendimiento (IN p_ID_RENDIMIENTO int, IN p_ID_ACTIVIDAD int, IN p_ID_TIPO_RENDIMIENT int, IN p_ID_NINIO int, IN p_OBSERVACIONES text) 
BEGIN
    UPDATE rendimiento SET ID_ACTIVIDAD = p_ID_ACTIVIDAD, ID_TIPO_RENDIMIENT = p_ID_TIPO_RENDIMIENT, ID_NINIO = p_ID_NINIO, OBSERVACIONES = p_OBSERVACIONES WHERE ID_RENDIMIENTO = p_ID_RENDIMIENTO;
END $$

CREATE PROCEDURE Eliminar_rendimiento (IN p_ID_RENDIMIENTO int) 
BEGIN
    DELETE FROM rendimiento WHERE ID_RENDIMIENTO = p_ID_RENDIMIENTO;
END $$

CREATE PROCEDURE ObtenerTodos_rendimiento () 
BEGIN
    SELECT * FROM rendimiento;
END $$

CREATE PROCEDURE Insertar_salud_alergias_relation (IN p_ID_ALERGIA int, IN p_ID_SALUD_STAT int) 
BEGIN
    INSERT INTO salud_alergias_relation (ID_ALERGIA, ID_SALUD_STAT) VALUES (p_ID_ALERGIA, p_ID_SALUD_STAT);
END $$

CREATE PROCEDURE ObtenerTodos_salud_alergias_relation () 
BEGIN
    SELECT * FROM salud_alergias_relation;
END $$

CREATE PROCEDURE Insertar_salud_medicament_relation (IN p_ID_MEDICAMENTO int, IN p_ID_SALUD_STAT int) 
BEGIN
    INSERT INTO salud_medicament_relation (ID_MEDICAMENTO, ID_SALUD_STAT) VALUES (p_ID_MEDICAMENTO, p_ID_SALUD_STAT);
END $$

CREATE PROCEDURE ObtenerTodos_salud_medicament_relation () 
BEGIN
    SELECT * FROM salud_medicament_relation;
END $$

CREATE PROCEDURE Insertar_talla_vestimenta (IN p_NUMERO_TALLA decimal(4,0)) 
BEGIN
    INSERT INTO talla_vestimenta (NUMERO_TALLA) VALUES (p_NUMERO_TALLA);
END $$

CREATE PROCEDURE Actualizar_talla_vestimenta (IN p_ID_TALLA_VESTIMENTA int, IN p_NUMERO_TALLA decimal(4,0)) 
BEGIN
    UPDATE talla_vestimenta SET NUMERO_TALLA = p_NUMERO_TALLA WHERE ID_TALLA_VESTIMENTA = p_ID_TALLA_VESTIMENTA;
END $$

CREATE PROCEDURE Eliminar_talla_vestimenta (IN p_ID_TALLA_VESTIMENTA int) 
BEGIN
    DELETE FROM talla_vestimenta WHERE ID_TALLA_VESTIMENTA = p_ID_TALLA_VESTIMENTA;
END $$

CREATE PROCEDURE ObtenerTodos_talla_vestimenta () 
BEGIN
    SELECT * FROM talla_vestimenta;
END $$

CREATE PROCEDURE Insertar_talla_zapato (IN p_NUMERO_TALLA decimal(4,0)) 
BEGIN
    INSERT INTO talla_zapato (NUMERO_TALLA) VALUES (p_NUMERO_TALLA);
END $$

CREATE PROCEDURE Actualizar_talla_zapato (IN p_ID_TALLA_ZAPATO int, IN p_NUMERO_TALLA decimal(4,0)) 
BEGIN
    UPDATE talla_zapato SET NUMERO_TALLA = p_NUMERO_TALLA WHERE ID_TALLA_ZAPATO = p_ID_TALLA_ZAPATO;
END $$

CREATE PROCEDURE Eliminar_talla_zapato (IN p_ID_TALLA_ZAPATO int) 
BEGIN
    DELETE FROM talla_zapato WHERE ID_TALLA_ZAPATO = p_ID_TALLA_ZAPATO;
END $$

CREATE PROCEDURE ObtenerTodos_talla_zapato () 
BEGIN
    SELECT * FROM talla_zapato;
END $$

CREATE PROCEDURE Insertar_tipo_rendimiento (IN p_NOMBRE_RENDIMIENT varchar(20)) 
BEGIN
    INSERT INTO tipo_rendimiento (NOMBRE_RENDIMIENT) VALUES (p_NOMBRE_RENDIMIENT);
END $$

CREATE PROCEDURE Actualizar_tipo_rendimiento (IN p_ID_TIPO_RENDIMIENT int, IN p_NOMBRE_RENDIMIENT varchar(20)) 
BEGIN
    UPDATE tipo_rendimiento SET NOMBRE_RENDIMIENT = p_NOMBRE_RENDIMIENT WHERE ID_TIPO_RENDIMIENT = p_ID_TIPO_RENDIMIENT;
END $$

CREATE PROCEDURE Eliminar_tipo_rendimiento (IN p_ID_TIPO_RENDIMIENT int) 
BEGIN
    DELETE FROM tipo_rendimiento WHERE ID_TIPO_RENDIMIENT = p_ID_TIPO_RENDIMIENT;
END $$

CREATE PROCEDURE ObtenerTodos_tipo_rendimiento () 
BEGIN
    SELECT * FROM tipo_rendimiento;
END $$

CREATE PROCEDURE Insertar_tutor (IN p_ID_NACIONALIDAD int, IN p_ID_GENERO int, IN p_ID_PARENTESCO int, IN p_NOMBRE_TUTOR varchar(30), IN p_APELLIDO_TUTOR varchar(30), IN p_CI_TUTOR varchar(10), IN p_DIRECCION_TUTOR varchar(30), IN p_TELEFONO_TUTOR varchar(10), IN p_DOMICILIO_TUTOR varchar(30), IN p_MOTIVO text) 
BEGIN
    INSERT INTO tutor (ID_NACIONALIDAD, ID_GENERO, ID_PARENTESCO, NOMBRE_TUTOR, APELLIDO_TUTOR, CI_TUTOR, DIRECCION_TUTOR, TELEFONO_TUTOR, DOMICILIO_TUTOR, MOTIVO) VALUES (p_ID_NACIONALIDAD, p_ID_GENERO, p_ID_PARENTESCO, p_NOMBRE_TUTOR, p_APELLIDO_TUTOR, p_CI_TUTOR, p_DIRECCION_TUTOR, p_TELEFONO_TUTOR, p_DOMICILIO_TUTOR, p_MOTIVO);
END $$

CREATE PROCEDURE Actualizar_tutor (IN p_ID_TUTOR int, IN p_ID_NACIONALIDAD int, IN p_ID_GENERO int, IN p_ID_PARENTESCO int, IN p_NOMBRE_TUTOR varchar(30), IN p_APELLIDO_TUTOR varchar(30), IN p_CI_TUTOR varchar(10), IN p_DIRECCION_TUTOR varchar(30), IN p_TELEFONO_TUTOR varchar(10), IN p_DOMICILIO_TUTOR varchar(30), IN p_MOTIVO text) 
BEGIN
    UPDATE tutor SET ID_NACIONALIDAD = p_ID_NACIONALIDAD, ID_GENERO = p_ID_GENERO, ID_PARENTESCO = p_ID_PARENTESCO, NOMBRE_TUTOR = p_NOMBRE_TUTOR, APELLIDO_TUTOR = p_APELLIDO_TUTOR, CI_TUTOR = p_CI_TUTOR, DIRECCION_TUTOR = p_DIRECCION_TUTOR, TELEFONO_TUTOR = p_TELEFONO_TUTOR, DOMICILIO_TUTOR = p_DOMICILIO_TUTOR, MOTIVO = p_MOTIVO WHERE ID_TUTOR = p_ID_TUTOR;
END $$

CREATE PROCEDURE Eliminar_tutor (IN p_ID_TUTOR int) 
BEGIN
    DELETE FROM tutor WHERE ID_TUTOR = p_ID_TUTOR;
END $$

CREATE PROCEDURE ObtenerTodos_tutor () 
BEGIN
    SELECT * FROM tutor;
END $$

CREATE PROCEDURE Insertar_tutores_ninios_relation (IN p_ID_NINIO int, IN p_ID_TUTOR int) 
BEGIN
    INSERT INTO tutores_ninios_relation (ID_NINIO, ID_TUTOR) VALUES (p_ID_NINIO, p_ID_TUTOR);
END $$

CREATE PROCEDURE ObtenerTodos_tutores_ninios_relation () 
BEGIN
    SELECT * FROM tutores_ninios_relation;
END $$

DELIMITER ;
